name: Build Bluesky Web

on:
  push:
    branches: [ test ]

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Install Node.js Version 22
        uses: actions/setup-node@v3
        with:
          node-version: '22.14.0'
  
      - name: Install Yarn Dependencies
        run: |
          yarn cache clean
          yarn install
          yarn add -D webpack-cli
          
      - name: Build Web Version
        run: yarn build-web

      - name: Run Server in Dev
        run: yarn start:dev
