name: CIS-565-Build

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Build Project
      run: npm run build

    - name: Install Playwright Browsers
      uses: microsoft/playwright-github-action@v1

    - name: Run Playwright Tests
      run: npx playwright test --reporter=html

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 1
