name: raw-build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  raw-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: false
          # Optionally, specify a tag for the local image:
          # tags: myimage:latest
