name: Playwright Systems Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-login-system-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js Package
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Verify Playwright Browsers
        run: npx playwright install

      - name: Install Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y allure
          npm install -D allure-playwright

      - name: Run Playwright tests
        run: xvfb-run npx playwright test --grep @login --reporter=line,allure-playwright
        env:
          CIS565_EMAIL: ${{ secrets.CIS565_EMAIL}}
          CIS565_PASSWORD: ${{ secrets.CIS565_EMAIL}}

      - name: Generate Allure report
        run: allure generate allure-results --clean -o allure-report

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-login-ui-report
          path: allure-report/
          retention-days: 30

  run-search-system-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js Package
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Verify Playwright Browsers
        run: npx playwright install

      - name: Install Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y allure
          npm install -D allure-playwright

      - name: Run Playwright tests
        run: xvfb-run npx playwright test --grep @search --reporter=line,allure-playwright

      - name: Generate Allure report
        run: allure generate allure-results --clean -o allure-report

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-search-ui-report
          path: allure-report/
          retention-days: 30
