name: Playwright Systems Tests (V.2)

# Automate Github actions
on:
  # Remote push request to 'main' repo, run below job
  push:
    branches: [ main ]

  # Manual github actions calls, run below job
  workflow_dispatch:

# Automated job definition
jobs:
  # Test Login UI functionality
  run-login-system-tests:
    # After 1hr stop job if not completed
    timeout-minutes: 60

    # Run on github's linux environment
    runs-on: ubuntu-latest

    # Steps definition
    steps:
      # Using the github action built-in cmds, checkout the repo
    - name: Checkout Code
      uses: actions/checkout@v4

      # Setup node.js package
    - name: Setup Node.js Package
      uses: actions/setup-node@v4
      # Specify which node version (i.e. the latest version)
      with:
        node-version: lts/*

      # Install any node dependencies needed
    - name: Install dependencies
      run: npm ci

      # Install Playwright browsers (i.e. Chromium, Webkit, Firefox) with dependencies
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

      # Install Allure command-line tool and Allure Playwright reporter
    - name: Install Allure
      run: |
        sudo apt-get update
        sudo apt-get install -y allure
        npm install -D @playwright/test allure-playwright

      # Run the playwright test scripts with Allure reporter
    - name: Run Playwright tests
      run: xvfb-run npx playwright test --grep @login --reporter=line,allure-playwright
      env:
        CIS565_EMAIL: ${{ secrets.CIS565_EMAIL}}
        CIS565_PASSWORD: ${{ secrets.CIS565_EMAIL}}

      # Generate Allure report
    - name: Generate Allure report
      run: allure generate allure-results --clean -o allure-report

      # Upload the Allure report as an artifact
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-login-ui-report
        path: allure-report/
        retention-days: 30

  # Test Search UI functionality
  run-search-system-tests:
    # After 1hr stop job if not completed
    timeout-minutes: 60

    # Run on github's linux environment
    runs-on: ubuntu-latest

    # Steps definition
    steps:
      # Using the github action built-in cmds, checkout the repo
    - name: Checkout Code
      uses: actions/checkout@v4

      # Setup node.js package
    - name: Setup Node.js Package
      uses: actions/setup-node@v4
      # Specify which node version (i.e. the latest version)
      with:
        node-version: lts/*

      # Install any node dependencies needed
    - name: Install dependencies
      run: npm ci

      # Install Playwright browsers (i.e. Chromium, Webkit, Firefox) with dependencies
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

      # Install Allure command-line tool and Allure Playwright reporter
    - name: Install Allure
      run: |
        sudo apt-get update
        sudo apt-get install -y allure
        npm install -D @playwright/test allure-playwright

      # Run the playwright test scripts with Allure reporter
    - name: Run Playwright tests
      run: xvfb-run npx playwright test --grep @search --reporter=line,allure-playwright

      # Generate Allure report
    - name: Generate Allure report
      run: allure generate allure-results --clean -o allure-report

      # Upload the Allure report as an artifact
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-search-ui-report
        path: allure-report/
        retention-days: 30
