name: Build Bluesky Web

on:
  push:
    branches: [ main ]

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Install Node.js Version 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'
  
      - name: Install Yarn Dependencies
        run: |
          yarn --frozen-lockfile --silent
          
      - name: Build Web Version
        run: yarn web
