name: Sample Test Pipeline

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  setup-backend:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          
      - name: Install Yarn Dependencies
        run: yarn install

      - name: Build Yarn
        run: yarn build
        
