name: Build & Test Bluesky Social Using Playwright

# Triggers
on:
  push:
    # Trigger CI/CD pipeline automation whenever new changes are 'push' to 'main' branch
    branches: [ develop ]

# Define Automated Jobs & Steps
jobs:
  # First Job: Build Workflow
  build:
    name: Build BlueSky Web App
    # Will automatically cancel workflow after 1 hour of running
    timeout-minutes: 60
    # Run Workflow using Ubuntu-22.04 OS
    runs-on: ubuntu-22.04

    # Step Definitions
    steps:
        # Checkout the latest code from the main repo
      - name: Checkout Git Repository
        uses: actions/checkout@v4

        # Setup Node.js required environment using v20
      - name: Setup Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use Node.js v20
          cache: 'yarn' # Enable caching for Yarn dependencies

        # Install Yarn package manager dependencies
      - name: Install Yarn Dependencies
        run: yarn

        # Start blueSky server local instance (in background)
      - name: Start BlueSky Web Server In Background
        run: yarn web
